spring:
  profiles:
    active: dev

  application:
    name: sms
  main:
    allow-circular-references: true
    resources:
      static-locations:
        - classpath:/static/**
        - file:/static/uploads/**

  # Config package chứa file view JSP
  thymeleaf:
    prefix: classpath:/templates/webapp/views/
    suffix: .jsp
    cache: false
    encoding: UTF-8